== Tools

* https://getbukkit.org/download/spigot                    -> Downlod Spigot Server
* https://papermc.io/downloads                             -> Paper MC Server
* https://www.spigotmc.org/resources/categories/spigot.4/  -> Plugins


== Mumble

* https://www.mumble.info/                                  -> teamspeak
* https://registry.hub.docker.com/r/phlak/mumble            -> docker server img

see $WIDO_HOME/bin/other/mumble-run.sh

----
docker start mumble-server
docker stop mumble-server
----

Edit Config (serverpassword):

----
docker exec -it mumble-server vi /etc/mumble/config.ini
docker volume inspect mumble-data -> shows real dir to config
----

== Spigot Config:

/home/wiki/minecraft/ops.json

Make user to superuser:

----
[
  {
    "uuid": "fa9efe65-5152-440b-a7df-33fc309f617e",
    "name": "heywiki",
    "level": 4,
    "bypassesPlayerLimit": false
  }
]
----

(you can see uuid on the server console when server starts up)

== Superuser Commands

----
/weather rain
/weahter clear

/time set day
/time set night

/plugins
----

== server.properties

https://minecraft.gamepedia.com/Server.properties

* gamemode=surviva|creative|adventure
* difficulty=peaceful|easy|normal|hard

== Dev Plugin  se

=== UUID Finder

* https://dev.bukkit.org/projects/uuid-finder
* UUIDFinder.jar

/uuidfinder:uuidfinder gabrilux

== Mods

* https://www.youtube.com/watch?v=fNdET-oDD2k
* https://www.youtube.com/watch?v=p5Gt1B4Pctk     -> ASSEMBLY MOD!

=== Assembly Mod

* https://lekoopa.de.tl/Assembly-Mod.htm
* http://tennoxmods.blogspot.com/p/download.html    -> download


http://files.minecraftforge.net/   -> mincraft forge required

https://github.com/TeNNoX-Mods/

(unfortunately no source code!) -> use https://github.com/PowerCraft


-> forge is client side!

ServerSide: https://github.com/dmulloy2/AutoCraft/tree/master/src/main/java/net/dmulloy2/autocraft/types

"Currently, as of 2020, the modding community is split up between Forge and Fabric. 
Server modding is split up between CraftBukkit, Spigot, PaperMC and Sponge. 
Server linking software is split between
BungeeCord and Waterfall.[citation needed]

=== Spigot Plugins

https://www.youtube.com/watch?v=v4zbqtpLaS4&list=PLfu_Bpi_zcDNEKmR82hnbv9UxQ16nUBF7
https://github.com/AlvinVrolijk/ConveyorBelt
