#!/bin/bash

#executed before server is launched
# Idea is to have a standard set of config files (other then generated by start) if they don't exists
# in data yet, they get overwritten

#test
#setup=/home/tester/minecraft/HeywikiPaperServer/setup
#data=/home/tester/minecraft/HeywikiPaperServer/build

#prod
setup=/opt/minecraft
data=/data

echo "$setup"
echo "$data"

if [ ! -e $data/server.properties ]; then
    echo "setup server.properties"
  cp $setup/server.properties $data
fi


if [ ! -e $data/ops.json ]; then
  echo "setup ops.json"
  cp $setup/ops.json $data
fi
